name: Build

on:
  pull_request:
    types: [ opened, reopened, synchronize ]
    branches: [ "*" ]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: Install npm dependencies
        run: npm i
      - name: Lint
        run: npm run lint
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: Install npm dependencies
        run: npm i
      - name: Lint
        run: npm run test
